# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73abf9005557e46ea40e8ed958f24026c91ea1fef5c39714cb60d903c5d16295b5913c7e3e66c24f42a39fd12920c9b9a7872d8e11cfe020d63a1015719a6a97

test:
  secret_key_base: 2294b4923f09ba7b50f657b582339b03727e1da05006b62fdf090d3ad2d21d56c5f8c980a5b806cde6233d88767d7970a56b6e247abdfdf5d10266a4db9c85b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
